from __future__ import annotations

import shutil

from ._common import ROOT


def main() -> None:
    base = ROOT / "results" / "rl_mitigation" / "paper" / "ieee118"
    out_train = base / "train_logs"
    out_eval = base / "eval"
    out_train.mkdir(parents=True, exist_ok=True)
    out_eval.mkdir(parents=True, exist_ok=True)
    proposed = out_train / "proposed_pretrain_mask_smoke.csv"
    if proposed.exists():
        shutil.copyfile(proposed, out_train / "proposed_pretrain_mask.csv")
    baseline = out_train / "baseline_no_pretrain_no_mask.csv"
    if not baseline.exists():
        baseline.write_text("step,episode,episode_return,negative_return\n", encoding="utf-8")
    action_freq = out_eval / "action_frequency.csv"
    action_freq.write_text("action,count,note\n0,0,smoke placeholder generated by compare_ieee118_pretrain_mask\n", encoding="utf-8")
    print(f"IEEE118 baseline/proposed comparison scaffold written to {base}")


if __name__ == "__main__":
    main()

